[tool.poetry]
name = "etl-backup-case"
version = "0.1.0"
description = ""
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
boto3 = "^1.35.31"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"